export const METIERS_DOMAINES = [
  { value: '', label: 'Toutes les catégories' },
  { value: 'Médecin', label: 'Médecin / Santé' },
  { value: 'Dentiste', label: 'Dentiste / Santé' },
  { value: 'Pharmacie', label: 'Pharmacie / Santé' },
  { value: 'Kinésithérapeute', label: 'Kinésithérapeute / Santé' },
  { value: 'Infirmier', label: 'Infirmier / Santé' },
  { value: 'Psychologue', label: 'Psychologue / Santé' },
  { value: 'Vétérinaire', label: 'Vétérinaire / Santé' },
  { value: 'Avocat', label: 'Avocat / Juridique' },
  { value: 'Notaire', label: 'Notaire / Juridique' },
  { value: 'Huissier', label: 'Huissier / Juridique' },
  { value: 'Expert-comptable', label: 'Expert-comptable / Finance' },
  { value: 'Banque', label: 'Banque / Finance' },
  { value: 'Assurance', label: 'Assurance / Finance' },
  { value: 'Architecte', label: 'Architecte / Construction' },
  { value: 'Ingénieur', label: 'Ingénieur / Construction' },
  { value: 'Maçon', label: 'Maçon / Construction' },
  { value: 'Électricien', label: 'Électricien / Construction' },
  { value: 'Plombier', label: 'Plombier / Construction' },
  { value: 'Menuisier', label: 'Menuisier / Construction' },
  { value: 'Peintre', label: 'Peintre / Construction' },
  { value: 'Restaurant', label: 'Restaurant / Alimentation' },
  { value: 'Café', label: 'Café / Alimentation' },
  { value: 'Pâtisserie', label: 'Pâtisserie / Alimentation' },
  { value: 'Boulangerie', label: 'Boulangerie / Alimentation' },
  { value: 'Supermarché', label: 'Supermarché / Commerce' },
  { value: 'Épicerie', label: 'Épicerie / Commerce' },
  { value: 'Coiffeur', label: 'Coiffeur / Beauté' },
  { value: 'Esthéticienne', label: 'Esthéticienne / Beauté' },
  { value: 'Salon de beauté', label: 'Salon de beauté / Beauté' },
  { value: 'Garage', label: 'Garage / Automobile' },
  { value: 'Mécanicien', label: 'Mécanicien / Automobile' },
  { value: 'Carrossier', label: 'Carrossier / Automobile' },
  { value: 'École', label: 'École / Éducation' },
  { value: 'Université', label: 'Université / Éducation' },
  { value: 'Centre de formation', label: 'Centre de formation / Éducation' },
  { value: 'Hôtel', label: 'Hôtel / Tourisme' },
  { value: 'Agence de voyage', label: 'Agence de voyage / Tourisme' },
  { value: 'Location de voitures', label: 'Location de voitures / Tourisme' },
  { value: 'Agence immobilière', label: 'Agence immobilière / Immobilier' },
  { value: 'Informatique', label: 'Informatique / Technologie' },
  { value: 'Développeur web', label: 'Développeur web / Technologie' },
  { value: 'Graphiste', label: 'Graphiste / Communication' },
  { value: 'Photographe', label: 'Photographe / Communication' },
  { value: 'Imprimerie', label: 'Imprimerie / Communication' },
  { value: 'Transporteur', label: 'Transporteur / Transport' },
  { value: 'Taxi', label: 'Taxi / Transport' },
  { value: 'Pressing', label: 'Pressing / Services' },
  { value: 'Blanchisserie', label: 'Blanchisserie / Services' },
  { value: 'Nettoyage', label: 'Nettoyage / Services' },
];
